# Generated by Django 2.1.7 on 2019-04-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('rss_link', models.URLField()),
                ('publisher', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aricles', to='feeds.Feed')),
            ],
        ),
    ]
